//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishLearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ELTask()
        {
            this.UserELTask = new HashSet<UserELTask>();
        }
    
        public int TaskId { get; set; }
        public int AuthorId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Text { get; set; }
        public string Group { get; set; }
        public string DocumentPath { get; set; }
        public string Difficult { get; set; }
        public Nullable<int> LectionId { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> GrammarId { get; set; }
        public Nullable<int> TextId { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserELTask> UserELTask { get; set; }
        public virtual GrammarGroup GrammarGroup { get; set; }
        public virtual Lection Lection { get; set; }
        public virtual Test Test { get; set; }
        public virtual TextTask TextTask { get; set; }
    }
}
