//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishLearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grammar
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string Translate { get; set; }
        public int GroupId { get; set; }
        public byte[] Voice { get; set; }
        public int AuthorId { get; set; }
    
        public virtual GrammarGroup GrammarGroup { get; set; }
        public virtual User User { get; set; }
    }
}
