//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishLearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningWord
    {
        public int LearningWordId { get; set; }
        public int WordId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> LearnedDate { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public double LearnPercent { get; set; }
        public Nullable<System.DateTime> ExcerciseDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual Word Word { get; set; }
    }
}
