//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishLearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lection()
        {
            this.ELTask = new HashSet<ELTask>();
        }
    
        public int LectionId { get; set; }
        public string Name { get; set; }
        public int OwnerId { get; set; }
        public int LectionType { get; set; }
        public string Description { get; set; }
        public byte[] LectionText { get; set; }
        public Nullable<bool> Editable { get; set; }
        public string ExportOwner { get; set; }
        public string Complexity { get; set; }
        public int ComplexityOrder { get; set; }
        public string LectionPath { get; set; }
    
        public virtual User User { get; set; }
        public virtual LectionGroup LectionGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ELTask> ELTask { get; set; }
    }
}
