//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishLearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestHistory
    {
        public int TestHistoryId { get; set; }
        public int UserId { get; set; }
        public int TestId { get; set; }
        public System.DateTime PassDate { get; set; }
        public double SuccessPercent { get; set; }
        public string Questions { get; set; }
        public string Answers { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
    }
}
