//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishLearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test()
        {
            this.Question = new HashSet<Question>();
            this.TestHistory = new HashSet<TestHistory>();
        }
    
        public int TestId { get; set; }
        public string Name { get; set; }
        public int OwnerId { get; set; }
        public string Difficult { get; set; }
        public int TaskCount { get; set; }
        public int TestType { get; set; }
        public Nullable<bool> Editable { get; set; }
        public string ExportOwner { get; set; }
        public int Time { get; set; }
        public string Text { get; set; }
        public string Voice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Question { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestHistory> TestHistory { get; set; }
        public virtual TestGroup TestGroup { get; set; }
    }
}
